var CallbackID = {
    ADD_DPAD_CALLBACK: 0,
    UPDATE_SCORE_CALLBACK: 1,
    UPDATE_SCORE_BEST_CALLBACK: 2,
    GET_POSSIBLE_SLOTS: 3,
    GET_BOTTOM_SLOTS: 4,
    GET_AUTO_SLOTS: 5,
    CARD_ACCEPTED: 6,
    LOAD_TABLE: 7,
    INIT_TABLE: 8,
    SAVE_TIME: 9,
    RESTORE_TIME_CALLBACK: 10,
    RESET_GAME: 11,
    UNDO: 12
};